//! Communicating a context selection back to the invoking shell.
//!
//! A child process cannot change its parent's environment, and kctx must never write to the
//! user's kubeconfig files. So instead of editing anything, kctx generates a tiny *overlay*
//! kubeconfig that contains nothing but a `current-context` key and prepends it to the
//! `KUBECONFIG` path list it prints:
//!
//! ```text
//! ~/.cache/kctx/contexts/production-eu.yaml:~/.kube/prod.yaml
//! ```
//!
//! kubeconfig merging takes `current-context` from the first file that sets it (this is
//! client-go's rule, and `kube::config::Kubeconfig::merge` implements the same), so the
//! selected context wins while every cluster, user and credential keeps being read from the
//! user's untouched original file. No credential is ever copied.

use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::Context as _;

use crate::kubeconfig::ContextEntry;
use crate::paths;

/// The result of selecting a context: what to print, and what it refers to.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Selection {
    /// Value for `KUBECONFIG`: overlay path plus source path, joined with `:`.
    pub kubeconfig: String,
    /// The selected context name.
    pub context: String,
    /// The kubeconfig file defining the context.
    pub source: PathBuf,
    /// The generated overlay file, absent when the source already selects this context.
    pub overlay: Option<PathBuf>,
}

/// Prepare a selection, writing an overlay file only when one is actually needed.
pub fn prepare(entry: &ContextEntry) -> anyhow::Result<Selection> {
    let dir = paths::overlay_dir()
        .context("cannot determine a cache directory (neither $XDG_CACHE_HOME nor $HOME is set)")?;
    prepare_in(entry, &dir)
}

/// [`prepare`] with an explicit overlay directory, so tests never touch the real cache.
pub fn prepare_in(entry: &ContextEntry, dir: &Path) -> anyhow::Result<Selection> {
    // The file already points at this context, so plain `KUBECONFIG=<file>` is enough and we
    // can avoid writing anything at all.
    if entry.current_in_source {
        return Ok(Selection {
            kubeconfig: entry.source.display().to_string(),
            context: entry.name.clone(),
            source: entry.source.to_path_buf(),
            overlay: None,
        });
    }

    let overlay = overlay_path(dir, &entry.name);
    write_overlay(&overlay, &entry.name)
        .with_context(|| format!("writing overlay {}", overlay.display()))?;

    Ok(Selection {
        kubeconfig: format!("{}:{}", overlay.display(), entry.source.display()),
        context: entry.name.clone(),
        source: entry.source.to_path_buf(),
        overlay: Some(overlay),
    })
}

/// Overlay file for a context name.
///
/// One stable file per context rather than per invocation: two shells selecting different
/// contexts must never share a file, or one would retroactively change the other's context.
pub fn overlay_path(dir: &Path, context: &str) -> PathBuf {
    dir.join(format!("{}.yaml", paths::encode_file_stem(context)))
}

/// Render the overlay document for `context`.
///
/// The context name is serialised as JSON, which is a valid YAML double-quoted scalar — that
/// keeps names containing quotes, colons or `#` from breaking the document without pulling in a
/// YAML serialiser.
fn overlay_document(context: &str) -> String {
    let quoted = serde_json::to_string(context).expect("serialising a string cannot fail");
    format!(
        "# Generated by kctx. Selects an existing context by name.\n\
         # Contains no credentials and overrides nothing else.\n\
         apiVersion: v1\n\
         kind: Config\n\
         current-context: {quoted}\n"
    )
}

/// Write the overlay unless an identical file is already there.
fn write_overlay(path: &Path, context: &str) -> anyhow::Result<()> {
    use std::os::unix::fs::OpenOptionsExt;

    let document = overlay_document(context);
    if std::fs::read_to_string(path).is_ok_and(|existing| existing == document) {
        tracing::debug!(path = %path.display(), "overlay already current");
        return Ok(());
    }

    let dir = path
        .parent()
        .context("overlay path has no parent directory")?;
    paths::ensure_private_dir(dir)?;

    // Write-then-rename so a concurrent reader never sees a half-written document.
    let temporary = path.with_extension(format!("tmp{}", std::process::id()));
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(&temporary)?;
    file.write_all(document.as_bytes())?;
    file.sync_all()?;
    drop(file);
    std::fs::rename(&temporary, path)?;

    tracing::debug!(path = %path.display(), "overlay written");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kubeconfig::AuthMethod;
    use kube::config::Kubeconfig;
    use std::os::unix::fs::PermissionsExt;
    use std::sync::Arc;

    fn entry(name: &str, source: &Path, current_in_source: bool) -> ContextEntry {
        ContextEntry {
            name: name.to_string(),
            cluster: "c".to_string(),
            user: None,
            namespace: None,
            server: None,
            cluster_missing: false,
            source: Arc::from(source),
            current_in_source,
            active: false,
            ambiguous: false,
            auth_method: AuthMethod::Unspecified,
        }
    }

    #[test]
    fn prepends_an_overlay_when_the_source_selects_another_context() {
        let dir = tempfile::tempdir().unwrap();
        let source = Path::new("/home/u/.kube/prod.yaml");

        let selection = prepare_in(&entry("production-eu", source, false), dir.path()).unwrap();
        let overlay = dir.path().join("production-eu.yaml");

        assert_eq!(
            selection.kubeconfig,
            format!("{}:{}", overlay.display(), source.display())
        );
        assert_eq!(selection.overlay.as_deref(), Some(overlay.as_path()));
        assert!(overlay.is_file());
    }

    #[test]
    fn writes_nothing_when_the_source_already_selects_the_context() {
        let dir = tempfile::tempdir().unwrap();
        let source = Path::new("/home/u/.kube/prod.yaml");

        let selection = prepare_in(&entry("production-eu", source, true), dir.path()).unwrap();

        assert_eq!(selection.kubeconfig, source.display().to_string());
        assert_eq!(selection.overlay, None);
        assert!(std::fs::read_dir(dir.path()).unwrap().next().is_none());
    }

    #[test]
    fn overlay_contains_only_a_context_name() {
        let dir = tempfile::tempdir().unwrap();
        prepare_in(&entry("prod", Path::new("/k/c.yaml"), false), dir.path()).unwrap();

        let written = std::fs::read_to_string(dir.path().join("prod.yaml")).unwrap();
        assert!(written.contains("current-context: \"prod\""), "{written}");
        for forbidden in [
            "token",
            "client-certificate",
            "password",
            "clusters",
            "users",
        ] {
            assert!(!written.contains(forbidden), "{forbidden} in {written}");
        }
    }

    #[test]
    fn overlay_is_only_readable_by_its_owner() {
        let dir = tempfile::tempdir().unwrap();
        prepare_in(&entry("prod", Path::new("/k/c.yaml"), false), dir.path()).unwrap();

        let mode = std::fs::metadata(dir.path().join("prod.yaml"))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600, "unexpected mode {:o}", mode & 0o777);
    }

    #[test]
    fn repeated_selection_is_idempotent_and_leaves_no_temporary_files() {
        let dir = tempfile::tempdir().unwrap();
        let entry = entry("prod", Path::new("/k/c.yaml"), false);

        let first = prepare_in(&entry, dir.path()).unwrap();
        let second = prepare_in(&entry, dir.path()).unwrap();

        assert_eq!(first, second);
        let files: Vec<_> = std::fs::read_dir(dir.path()).unwrap().flatten().collect();
        assert_eq!(files.len(), 1, "{files:?}");
    }

    #[test]
    fn different_contexts_never_share_an_overlay_file() {
        let dir = tempfile::tempdir().unwrap();
        let one = prepare_in(
            &entry("team a/prod", Path::new("/k/c.yaml"), false),
            dir.path(),
        )
        .unwrap();
        let two = prepare_in(
            &entry("team a_2fprod", Path::new("/k/c.yaml"), false),
            dir.path(),
        )
        .unwrap();

        assert_ne!(one.overlay, two.overlay);
    }

    #[test]
    fn awkward_context_names_stay_parseable() {
        let dir = tempfile::tempdir().unwrap();
        let name = "arn:aws:eks:eu-central-1:1234:cluster/prod # \"quoted\"";

        let selection =
            prepare_in(&entry(name, Path::new("/k/c.yaml"), false), dir.path()).unwrap();
        let parsed = Kubeconfig::read_from(selection.overlay.unwrap()).unwrap();

        assert_eq!(parsed.current_context.as_deref(), Some(name));
    }

    #[test]
    fn overlay_plus_source_merges_to_the_selected_context() {
        // The property the whole mechanism rests on: merging the overlay ahead of the user's
        // file yields the selected context, with clusters and users coming from the original.
        let dir = tempfile::tempdir().unwrap();
        let source_path = dir.path().join("prod.yaml");
        std::fs::write(
            &source_path,
            "apiVersion: v1\nkind: Config\ncurrent-context: staging\nclusters:\n  - name: c\n    cluster:\n      server: https://example.com\nusers:\n  - name: u\n    user:\n      token: secret\ncontexts:\n  - name: staging\n    context:\n      cluster: c\n      user: u\n  - name: production-eu\n    context:\n      cluster: c\n      user: u\n",
        )
        .unwrap();

        let selection =
            prepare_in(&entry("production-eu", &source_path, false), dir.path()).unwrap();
        let paths: Vec<&str> = selection.kubeconfig.split(':').collect();

        let merged = Kubeconfig::read_from(paths[0])
            .unwrap()
            .merge(Kubeconfig::read_from(paths[1]).unwrap())
            .unwrap();

        assert_eq!(merged.current_context.as_deref(), Some("production-eu"));
        assert_eq!(merged.clusters.len(), 1);
        assert_eq!(merged.contexts.len(), 2);
    }
}
